apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: app1
  namespace: qa1
spec:
  interval: 5m

  chart:
    spec:
      chart: .   # your chart is at repo root
      sourceRef:
        kind: GitRepository
        name: helm-charts-repo
        namespace: flux-system   # ✅ REQUIRED
      interval: 1m               # ✅ recommended

  valuesFrom:
    - kind: ConfigMap
      name: app1-values



  # values:
  #   replicaCount: 2

  #   image:
  #     repository: your-docker-repo/app1
  #     tag: latest

  #   service:
  #     type: ClusterIP
  #     port: 80

  #   resources:
  #     limits:
  #       cpu: "500m"
  #       memory: "512Mi"