apiVersion: v1
kind: ConfigMap
metadata:
  name: app2-values
  namespace: qa1
data:
  values.yaml: |
    replicaCount: 2

    image:
      repository: nginx
      tag: latest

    service:
      port: 8080

    env:
      ENV: qa1

    ingress:
      enabled: true
      hosts:
        - host: app1.qa1.example.com